[package]
name = "parallelhash"
version = "0.1.0"
edition = "2021"

[dependencies]
rayon = "1.10.0"
clap = { version = "4.5.16", features = ["derive"] }
digest = "0.10.7"
sha1 = "0.10.6"
md-5 = "0.10.6"
sha2 = "0.10.8"
walkdir = "2.5.0"
hex = "0.4.3"
anyhow = "1.0.86"
crossbeam = "0.8.4"
